config file upload
vinhprs/Rensis_BackEnd pull request #1
Opened 2023-01-09 08:25 UTC by vinhprs

2023-01-09 08:30 UTC, killerburn69 approved these changes
OKe á em vinh

2023-01-11 14:29 UTC, phanhuutoan requested changes
E move cái config của cloudinary và cái util function vào thành 1 cái service, những các config ban đầu ném vào trong constructor, sau này có caching j cũng dễ sử dụng, ngoài ra cái function xóa file, update file cũng sẽ được implement trong service này.
Còn lại a thấy mọi thứ được code ổn.

2023-01-11 14:29 UTC, phanhuutoan commented on src/configs/cloudinary.config.ts
> +cloudinary.v2.config({
chuyển vào 1 file service

2023-01-11 14:29 UTC, phanhuutoan commented on src/utils/uploadFile.util.ts
> +export async function uploadFile(image: Promise<FileUpload>, folder: string)
chuyển vào 1 file service

2023-01-11 14:31 UTC, phanhuutoan requested changes

2023-01-11 14:31 UTC, phanhuutoan commented on src/common/entities/common.entity.ts
> +export interface FileUpload {
interface không phải là Entity đừng để chung file với nó

2023-01-30 06:35 UTC, vinhprs commented on src/utils/uploadFile.util.ts
> +export async function uploadFile(image: Promise<FileUpload>, folder: string)
đã update ạ

2023-01-30 06:35 UTC, vinhprs commented on src/common/entities/common.entity.ts
> +export interface FileUpload {
đã update ạ

2023-01-30 07:13 UTC, merged